# Generated by Django 4.2.24 on 2025-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('segmento', 'tecnologia', 'orden', 'velocidad_mbps'), 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='compresion',
            field=models.CharField(blank=True, default='2:1', help_text='Formato "2:1", "4:1", etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='moneda',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='segmento',
            field=models.CharField(choices=[('HOGAR', 'Home'), ('EMPRESA', 'Empresa')], default='HOGAR', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='simetrico',
            field=models.BooleanField(blank=True, default=True, help_text='Si la velocidad es simétrica', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tecnologia',
            field=models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('WIRELESS', 'Wireless')], default='FIBRA', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='destacado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='plan',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='velocidad_mbps',
            field=models.PositiveIntegerField(help_text='Velocidad nominal en Mbps (p.ej. 50, 100, 200…)'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('segmento', 'tecnologia', 'velocidad_mbps', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='precio',
        ),
        migrations.DeleteModel(
            name='Caracteristica',
        ),
    ]
