# Generated by Django 4.2.24 on 2025-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_plan_options_plan_activo_plan_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='icono',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
