# Generated by Django 4.2.24 on 2025-10-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_plan_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='compresion',
            field=models.CharField(blank=True, default='2:1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='simetrico',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='velocidad_mbps',
            field=models.PositiveIntegerField(help_text='Mbps'),
        ),
    ]
