# Generated by Django 4.2.24 on 2025-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_alter_plan_compresion_alter_plan_simetrico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='beneficio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='router',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
