# Generated by Django 4.2.24 on 2025-10-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_plan_beneficio_plan_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='n_pantalla_gomax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
