# Generated by Django 4.2.24 on 2025-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lema', models.CharField(blank=True, help_text='Frase corta o slogan', max_length=255)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, help_text='Número WhatsApp con código país', max_length=50)),
                ('whatsapp_ventas', models.CharField(blank=True, help_text='Número WhatsApp con código país', max_length=50)),
                ('whatsapp_info', models.CharField(blank=True, help_text='Número WhatsApp con código país', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario', models.CharField(blank=True, help_text='Ej. Lun-Vie 8:00-18:00', max_length=200)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Identificador en URL (ej: sobre-nosotros)', unique=True)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paginas/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Página institucional',
                'verbose_name_plural': 'Páginas institucionales',
            },
        ),
    ]
