# Generated by Django 4.2.24 on 2025-10-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_delete_mensajecontacto_alter_empresa_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='botarga_1',
            field=models.ImageField(blank=True, help_text='mascota empresa', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='botarga_2',
            field=models.ImageField(blank=True, help_text='mascota empresa', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='botarga_3',
            field=models.ImageField(blank=True, help_text='mascota empresa', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_1',
            field=models.ImageField(blank=True, help_text='Imagen 1 para inciio slider', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_2',
            field=models.ImageField(blank=True, help_text='Imagen 2 para inciio slider', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_3',
            field=models.ImageField(blank=True, help_text='Imagen 3 para inciio slider', null=True, upload_to='paginas/'),
        ),
    ]
