# Generated by Django 4.2.24 on 2025-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_pagina_botarga_1_pagina_botarga_2_pagina_botarga_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name': 'Página Inicio', 'verbose_name_plural': 'Página Inicio'},
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='slug',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
