# Generated by Django 4.2.24 on 2025-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_pagina_options_remove_pagina_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caract_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='caracteres/')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
