# Generated by Django 4.2.24 on 2025-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_caract_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caract_servicios',
            options={'verbose_name': 'Caracteristica de Servicios', 'verbose_name_plural': 'Caracteristica de Servicios'},
        ),
        migrations.AddField(
            model_name='caract_servicios',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caract_servicios',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
