# Generated by Django 4.2.24 on 2025-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_caract_servicios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='img_contacto',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
    ]
