# Generated by Django 4.2.24 on 2025-10-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_pagina_img_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='img_serv_hotspot',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_serv_vivo',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
    ]
