# Generated by Django 4.2.24 on 2025-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_pagina_img_serv_hotspot_pagina_img_serv_vivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('seguridad', 'Seguridad informática'), ('ancho_banda', 'Ancho de banda')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('sub_titulo', models.CharField(blank=True, max_length=250)),
                ('cuerpo', models.TextField(help_text='Puedes usar HTML básico (se mostrará con |safe).')),
                ('publicado', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
            ],
            options={
                'verbose_name': 'Información Web',
                'verbose_name_plural': 'Información Web',
            },
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(blank=True, default='RedPlus', max_length=200, null=True),
        ),
    ]
