# Generated by Django 4.2.24 on 2025-10-10 11:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_info_web_alter_pagina_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_web',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(help_text='Editor avanzado para el contenido'),
        ),
    ]
