# Generated by Django 4.2.24 on 2025-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_info_web_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='maps_link',
            field=models.URLField(blank=True, verbose_name='Link Google Maps (opcional)'),
        ),
    ]
