# Generated by Django 4.2.24 on 2025-10-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_empresa_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='maps_view',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='maps_link',
            field=models.URLField(blank=True, verbose_name='Link Google Maps (Ruta)'),
        ),
    ]
