# Generated by Django 4.2.24 on 2025-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_empresa_maps_view_alter_empresa_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='img_4',
            field=models.ImageField(blank=True, help_text='Imagen  para  Conéctate con nosotros', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_5',
            field=models.ImageField(blank=True, help_text='Imagen  para ', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_6',
            field=models.ImageField(blank=True, help_text='Imagen  para', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_7',
            field=models.ImageField(blank=True, help_text='Imagen  ', null=True, upload_to='paginas/'),
        ),
    ]
