# Generated by Django 4.2.24 on 2025-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_pagina_img_4_pagina_img_5_pagina_img_6_pagina_img_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('maps_link', models.URLField(blank=True, verbose_name='Link Google Maps (Ruta)')),
                ('maps_view', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, help_text='Número WhatsApp con código país', max_length=50)),
                ('whatsapp_ventas', models.CharField(blank=True, help_text='Número WhatsApp con código país', max_length=50)),
                ('whatsapp_info', models.CharField(blank=True, help_text='Número WhatsApp con código país', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario', models.CharField(blank=True, help_text='Ej. Lun-Vie 8:00-18:00', max_length=200)),
            ],
            options={
                'verbose_name': 'Sucursales',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
