# Generated by Django 4.2.24 on 2025-10-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='nombre',
        ),
    ]
