# Generated by Django 4.2.24 on 2025-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_remove_sucursal_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='img_gomax_1',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_gomax_2',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_gomax_3',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='maps_link',
            field=models.URLField(blank=True, help_text='aquí pegas el shortlink o url de google maps', verbose_name='Link Google Maps (Ruta)'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='maps_view',
            field=models.TextField(blank=True, help_text='aquí pegas el Incorporar un mapa de google maps sin el iframe src=', null=True),
        ),
    ]
