# Generated by Django 4.2.24 on 2025-10-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_pagina_img_gomax_1_pagina_img_gomax_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='archivo_calidad',
            field=models.FileField(blank=True, help_text='Subir archivo pdf dispuestos por la ARCOTEL', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='img_calidad',
            field=models.ImageField(blank=True, help_text='Imagen resolucion dispuestos por la ARCOTEL', null=True, upload_to='paginas/'),
        ),
    ]
