# Generated by Django 4.2.24 on 2025-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_pagina_archivo_calidad_pagina_img_calidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='img_consumo',
            field=models.ImageField(blank=True, null=True, upload_to='paginas/'),
        ),
    ]
