# Generated by Django 4.2.24 on 2025-10-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_pagina_img_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='img_informacion',
            field=models.ImageField(blank=True, help_text='Imagen horizontal sobre informacion al cliente', null=True, upload_to='paginas/'),
        ),
    ]
