# Generated by Django 4.2.24 on 2025-10-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_pagina_img_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
