# Generated by Django 4.2.24 on 2025-10-18 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_alter_empresa_facebook_alter_empresa_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('politica_regulaciones', 'Políticas y regulaciones'), ('legislacion_ayuda', 'Legislación y ayuda'), ('normas_beneficio', 'Normas y beneficios'), ('ayuda_rapida', 'Legislación y ayuda')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('sub_titulo', models.CharField(blank=True, max_length=250)),
                ('cuerpo', ckeditor.fields.RichTextField(help_text='Editor avanzado para el contenido')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Subir archivo en pdf', null=True, upload_to='paginas/')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
            ],
            options={
                'verbose_name': 'Documentacion',
                'verbose_name_plural': 'Documentacion',
            },
        ),
    ]
