# Generated by Django 4.2.24 on 2025-10-22 12:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_documentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='categoria',
            field=models.CharField(choices=[('politica_regulaciones', 'Políticas y regulaciones'), ('legislacion_ayuda', 'Legislación y ayuda'), ('normas_beneficio', 'Normas y beneficios'), ('ayuda_rapida', 'Ayuda Rápida')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Editor avanzado para el contenido', null=True),
        ),
    ]
