# Generated by Django 4.2.24 on 2025-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_alter_documentacion_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='activar_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='link',
            field=models.CharField(blank=True, help_text='Link de información', max_length=250, null=True),
        ),
    ]
