# Generated by Django 4.2.24 on 2025-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_documentacion_activar_link_documentacion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='detalle',
            field=models.TextField(blank=True, help_text='resumen de lo que es la empresa RedPlus', null=True),
        ),
    ]
