# Generated by Django 4.2.24 on 2025-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_empresa_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='test_velocidad',
            field=models.TextField(blank=True, help_text='Copiar aqui el frame codigo de test de velocidad', null=True),
        ),
    ]
