# Generated by Django 4.2.24 on 2025-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_empresa_test_velocidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='test_velocidad',
            field=models.TextField(blank=True, help_text='Copiar aqui el iframe  codigo de test de velocidad', null=True),
        ),
    ]
